const nodemailer = require('nodemailer');

// Create transporter — uses Gmail App Password from env
function createTransporter() {
  if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
    return nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,  // Gmail App Password (not your login password)
      },
    });
  }
  return null;
}

/* ─── OTP Email ─────────────────────────────────────────────────────────── */
async function sendOtpEmail(to, otp, userName = '') {
  const transporter = createTransporter();
  const html = `
    <div style="font-family:'Segoe UI',sans-serif;max-width:480px;margin:0 auto;background:#0a1628;color:#f1f5f9;border-radius:16px;overflow:hidden;">
      <div style="background:linear-gradient(135deg,#00bfff,#0080ff);padding:28px 32px;">
        <h1 style="margin:0;font-size:22px;font-weight:800;color:#fff;">⚡ EduPulse Password Reset</h1>
      </div>
      <div style="padding:32px;">
        <p style="margin:0 0 16px;font-size:15px;color:rgba(255,255,255,0.8);">Hi ${userName || 'there'},</p>
        <p style="margin:0 0 24px;font-size:15px;color:rgba(255,255,255,0.7);">Use the OTP below — it expires in <strong style="color:#00bfff;">10 minutes</strong>.</p>
        <div style="background:rgba(0,191,255,0.1);border:2px solid #00bfff;border-radius:12px;padding:20px;text-align:center;margin-bottom:24px;">
          <div style="font-size:36px;font-weight:800;letter-spacing:12px;color:#00bfff;">${otp}</div>
        </div>
        <p style="font-size:13px;color:rgba(255,255,255,0.4);margin:0;">If you didn't request this, ignore this email.</p>
      </div>
      <div style="background:rgba(255,255,255,0.04);padding:16px 32px;font-size:12px;color:rgba(255,255,255,0.3);">
        © ${new Date().getFullYear()} EduPulse — AI-Powered Academic Navigator
      </div>
    </div>
  `;
  if (!transporter) {
    console.log(`\n📧 [DEV - OTP not sent, no SMTP configured]`);
    console.log(`   To: ${to} | OTP: ${otp}\n`);
    return;
  }
  await transporter.sendMail({ from: `"EduPulse" <${process.env.EMAIL_USER}>`, to, subject: `Your EduPulse OTP: ${otp}`, html });
}

/* ─── Parent Alert Email ─────────────────────────────────────────────────── */
/**
 * Sends a rich HTML parent alert email when a student is at risk.
 * Called by:
 *   - alerts.js POST /api/alerts/send  (manual trigger by SCM)
 *   - cluster.js POST /api/cluster/run  (auto-trigger when K-Means → 'below')
 */
async function sendAlertEmail({ to, subject, content, studentName, scmName, scmEmail, cluster, attendance, healthScore }) {
  const transporter = createTransporter();

  const clusterColor = cluster === 'below' ? '#ef4444' : cluster === 'medium' ? '#f59e0b' : '#10b981';
  const clusterLabel = cluster === 'below' ? '⚠️ Below Average' : cluster === 'medium' ? '📊 Medium' : '✅ Top';

  const html = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
    <body style="margin:0;padding:0;background:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
      <div style="max-width:600px;margin:24px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

        <!-- Header -->
        <div style="background:linear-gradient(135deg,#1e3a5f,#0f2440);padding:28px 32px;display:flex;align-items:center;gap:16px;">
          <div style="background:rgba(255,255,255,0.15);border-radius:50%;width:48px;height:48px;display:flex;align-items:center;justify-content:center;font-size:24px;">🎓</div>
          <div>
            <div style="color:#fff;font-size:20px;font-weight:800;">EduPulse</div>
            <div style="color:rgba(255,255,255,0.6);font-size:12px;letter-spacing:1px;">AI-POWERED ACADEMIC NAVIGATOR</div>
          </div>
        </div>

        <!-- Alert Banner -->
        <div style="background:#fef2f2;border-left:4px solid #ef4444;padding:16px 32px;display:flex;align-items:center;gap:12px;">
          <span style="font-size:24px;">🚨</span>
          <div>
            <div style="font-size:14px;font-weight:700;color:#dc2626;">ACADEMIC PERFORMANCE ALERT</div>
            <div style="font-size:12px;color:#6b7280;margin-top:2px;">Auto-generated by EduPulse K-Means Intelligence System</div>
          </div>
        </div>

        <!-- Body -->
        <div style="padding:32px;">
          <p style="font-size:16px;color:#1e293b;margin:0 0 24px;">Dear Parent / Guardian,</p>

          <p style="font-size:14px;color:#475569;line-height:1.7;margin:0 0 24px;">
            Our AI monitoring system has detected that <strong style="color:#1e293b;">${studentName}</strong> 
            requires immediate attention. The following data was used to generate this alert:
          </p>

          <!-- Stats Cards -->
          <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-bottom:24px;">
            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;text-align:center;">
              <div style="font-size:11px;color:#94a3b8;font-weight:600;letter-spacing:1px;margin-bottom:4px;">CLUSTER</div>
              <div style="font-size:14px;font-weight:800;color:${clusterColor};">${clusterLabel}</div>
            </div>
            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;text-align:center;">
              <div style="font-size:11px;color:#94a3b8;font-weight:600;letter-spacing:1px;margin-bottom:4px;">ATTENDANCE</div>
              <div style="font-size:14px;font-weight:800;color:${(attendance||0)<75?'#ef4444':'#10b981'};">${attendance || 'N/A'}%</div>
            </div>
            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;text-align:center;">
              <div style="font-size:11px;color:#94a3b8;font-weight:600;letter-spacing:1px;margin-bottom:4px;">HEALTH SCORE</div>
              <div style="font-size:14px;font-weight:800;color:${(healthScore||0)<50?'#ef4444':'#f59e0b'};">${healthScore || 'N/A'}/100</div>
            </div>
          </div>

          <!-- AI Message -->
          <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:12px;padding:20px;margin-bottom:24px;">
            <div style="font-size:11px;color:#0284c7;font-weight:700;letter-spacing:1px;margin-bottom:10px;">🤖 AI ANALYSIS</div>
            <div style="font-size:14px;color:#0f172a;line-height:1.8;white-space:pre-line;">${content}</div>
          </div>

          <!-- CTA -->
          <div style="background:#f8fafc;border-radius:12px;padding:20px;margin-bottom:24px;">
            <div style="font-size:13px;font-weight:700;color:#1e293b;margin-bottom:8px;">📞 Immediate Action Required</div>
            <p style="font-size:13px;color:#475569;margin:0 0 12px;">Please schedule a meeting with your child's Student Career Manager as soon as possible.</p>
            <div style="font-size:13px;color:#1e293b;">
              <strong>SCM:</strong> ${scmName || 'Your Student Career Manager'}<br>
              <strong>Email:</strong> <a href="mailto:${scmEmail || 'scm@school.edu'}" style="color:#3b82f6;">${scmEmail || 'scm@school.edu'}</a>
            </div>
          </div>

          <!-- Research Stat -->
          <div style="background:#fef9c3;border:1px solid #fde047;border-radius:10px;padding:14px;font-size:12px;color:#713f12;">
            📊 <strong>Did you know?</strong> Students who receive early, data-driven intervention are <strong>3.2x more likely</strong> to recover academically compared to those flagged at semester end. <em>(Research-backed)</em>
          </div>
        </div>

        <!-- Footer -->
        <div style="background:#f8fafc;padding:20px 32px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8;text-align:center;">
          <div style="margin-bottom:4px;">© ${new Date().getFullYear()} EduPulse — AI-Powered Academic & Career Navigator</div>
          <div>This alert was auto-generated by EduPulse's K-Means Intelligence Engine. Do not reply to this email.</div>
        </div>
      </div>
    </body>
    </html>
  `;

  if (!transporter) {
    // Development fallback — log the alert
    console.log(`\n📧 [ALERT EMAIL — SMTP not configured, logging instead]`);
    console.log(`   To:      ${to}`);
    console.log(`   Subject: ${subject}`);
    console.log(`   Student: ${studentName} | Cluster: ${cluster} | Attendance: ${attendance}% | Health: ${healthScore}`);
    console.log(`   Content: ${content?.slice(0, 120)}...\n`);
    return { simulated: true, to, student: studentName };
  }

  const info = await transporter.sendMail({
    from: `"EduPulse Alert System" <${process.env.EMAIL_USER}>`,
    to,
    subject,
    html,
    text: `EduPulse Alert for ${studentName}\n\n${content}`,
  });

  return { messageId: info.messageId, to };
}

module.exports = { sendOtpEmail, sendAlertEmail };
