const express = require('express');
const router = express.Router();
const Alert = require('../models/Alert');
const Student = require('../models/Student');
const User = require('../models/User');
const { protect } = require('../middleware/auth');
const emailService = require('../services/emailService');
const geminiService = require('../services/geminiService');

// ── DEMO ENDPOINT (no auth required) ──────────────────
// POST /api/alerts/demo-alert
// Used by SCM dashboard to send a real email in demo mode.
router.post('/demo-alert', async (req, res) => {
  try {
    const { studentName, parentEmail, parentName, reason, alertType, attendance, healthScore, scmName, language } = req.body;

    const subject = `🚨 EduPulse Alert: ${studentName} — Immediate Attention Needed`;

    // Build rich email content based on alert type
    const alertEmoji = alertType === 'attendance' ? '📅' : alertType === 'academics' ? '📊' : '💛';
    const content = `Dear ${parentName || 'Parent/Guardian'},

${alertEmoji} This is an important update regarding your child ${studentName}'s academic progress.

Reason for Alert:
${reason}

Current Status:
• Attendance: ${attendance}% ${attendance < 75 ? '⚠️ BELOW REQUIRED 75%' : '✅'}
• Academic Health Score: ${healthScore}/100 ${healthScore < 50 ? '🔴 CRITICAL' : healthScore < 70 ? '🟡 NEEDS ATTENTION' : '🟢 GOOD'}

${attendance < 75 ? `⚠️ ATTENDANCE WARNING: ${studentName} needs to attend the next ${Math.ceil((0.75 * 100 - (attendance / 100 * 100)) / 0.25)} consecutive classes to restore compliance.\n` : ''}
We strongly encourage you to:
1. Connect with ${studentName} about their academic journey
2. Schedule a meeting with their SCM (Student Counseling Mentor)
3. Review the full dashboard on EduPulse for detailed insights

This message was generated by the EduPulse AI Monitoring System.`;

    await emailService.sendAlertEmail({
      to: parentEmail,
      subject,
      content,
      studentName,
      scmName: scmName || 'Prof. Ananya Sharma',
      scmEmail: 'ananya.sharma@college.edu'
    });

    res.json({
      success: true,
      message: `✅ Alert email sent to ${parentEmail}`,
      to: parentEmail,
      subject
    });
  } catch (err) {
    console.error('Demo alert email error:', err.message);
    res.status(500).json({ success: false, message: err.message });
  }
});



// POST /api/alerts/send
router.post('/send', protect, async (req, res) => {
  try {
    const { studentId, alertType, triggerReason, severity, language } = req.body;
    
    const student = await Student.findById(studentId);
    const parent = await User.findById(student.parentId);
    const scm = await User.findById(student.scmId);
    
    // Generate email content via Gemini
    let emailContent = '';
    let emailSubject = `EduPulse Alert: ${student.name} — ${alertType}`;
    
    try {
      emailContent = await geminiService.generateParentAlert({
        studentName: student.name,
        parentName: parent?.name || 'Parent/Guardian',
        semester: student.semester,
        department: student.department,
        triggerReason,
        alertType,
        attendancePercentage: student.attendancePercentage,
        academicHealthScore: student.academicHealthScore,
        language: language || 'en'
      });
    } catch (geminiError) {
      // Fallback email content
      emailContent = `Dear ${parent?.name || 'Parent/Guardian'},\n\nWe wanted to update you about ${student.name}'s academic progress.\n\nReason: ${triggerReason}\n\nPlease contact the SCM for more details.\n\nBest regards,\nEduPulse Team`;
    }
    
    // Save alert
    const alert = await Alert.create({
      studentId, alertType, triggerReason, severity: severity || 'medium',
      parentId: student.parentId, scmId: student.scmId,
      emailSubject, emailContent, sentAt: new Date()
    });
    
    // Send email
    if (parent?.email) {
      try {
        await emailService.sendAlertEmail({
          to: parent.email,
          subject: emailSubject,
          content: emailContent,
          studentName: student.name,
          scmName: scm?.name,
          scmEmail: scm?.email
        });
        alert.deliveredAt = new Date();
        await alert.save();
      } catch (emailError) {
        console.error('Email failed:', emailError.message);
      }
    }
    
    res.status(201).json(alert);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET /api/alerts/:parentId — alerts for a parent
router.get('/:parentId', protect, async (req, res) => {
  try {
    const alerts = await Alert.find({ parentId: req.params.parentId })
      .populate('studentId', 'name rollNumber department semester')
      .sort({ sentAt: -1 });
    res.json(alerts);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET /api/alerts/student/:studentId
router.get('/student/:studentId', protect, async (req, res) => {
  try {
    const alerts = await Alert.find({ studentId: req.params.studentId }).sort({ sentAt: -1 });
    res.json(alerts);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// PUT /api/alerts/:id/read
router.put('/:id/read', protect, async (req, res) => {
  try {
    const alert = await Alert.findByIdAndUpdate(req.params.id, { isRead: true }, { new: true });
    res.json(alert);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST /api/alerts/bulk-send
router.post('/bulk-send', protect, async (req, res) => {
  try {
    const { studentIds, alertType, triggerReason } = req.body;
    const results = [];
    
    for (const studentId of studentIds) {
      try {
        const student = await Student.findById(studentId);
        if (student) {
          const alert = await Alert.create({
            studentId, alertType, triggerReason,
            parentId: student.parentId, scmId: student.scmId,
            emailSubject: `EduPulse Alert: ${student.name}`,
            emailContent: triggerReason, sentAt: new Date()
          });
          results.push({ studentId, success: true, alertId: alert._id });
        }
      } catch (err) {
        results.push({ studentId, success: false, error: err.message });
      }
    }
    
    res.json({ sent: results.filter(r => r.success).length, failed: results.filter(r => !r.success).length, results });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
